// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqyovglhyvaafyextogk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxeW92Z2xoeXZhYWZ5ZXh0b2drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzQwNDYsImV4cCI6MjA3MjQxMDA0Nn0.AKSE1hRDaeMGa23MzNpV-OtTbmrTX5WY7Ng7EkdhzVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});